#!/usr/bin/env python3
"""Regenerates the wallpaper progress table inside the Obsidian vault's
CURRENT_STATE.md (between the PROGRESS markers) from what actually exists on
disk: tools/plan.json + catalog.json + work/ + scenes/ + dynamic/.
Run after every publish:  python3 ~/wallpaper-studio-library/tools/progress.py"""
import datetime, glob, json, os, re
L = os.path.expanduser("~/wallpaper-studio-library")
STATE = os.path.expanduser("~/Desktop/ObsidianVaults/ClaudeMemory/knowledge/Projects/WallpaperStudio/PROJECT_BRAIN/CURRENT_STATE.md")
plan = json.load(open(f"{L}/tools/plan.json"))
briefs = json.load(open(f"{L}/tools/briefs.json"))
catalog = json.load(open(f"{L}/catalog.json"))
published = {e["id"].split("-", 1)[1]: e for e in catalog}
planned = {p["slug"] for p in plan}

def status(p):
    s = p["slug"]
    if s in published and published[s]["kind"] == p["kind"]:
        return "✅ published"
    w = f"{L}/work/{s}"
    if glob.glob(f"{w}/final-r*.jpg") + glob.glob(f"{w}/final-r*.mp4") + glob.glob(f"{w}/day-r*.png"):
        return "🟡 finished, NOT published"
    if os.path.exists(f"{L}/scenes/{s}.metal") or os.path.exists(f"{w}/draft-scene.metal") or glob.glob(f"{w}/scene-r*.metal"):
        return "✏️ draft only"
    return "⬜ not started"

rows = [f"| {i+1} | {briefs.get(p['slug'], {}).get('title', p['slug'])} | `{p['slug']}` | {p['kind']}{' ('+str(round(p['frames']/30))+'s)' if p.get('frames') else ''} | {p.get('style','')} | {status(p)} | {('replaces '+p['replaces']) if p.get('replaces') else ''} |" for i, p in enumerate(plan)]
counts = {}
for p in plan:
    k = status(p).split(" ", 1)[1]
    counts[k] = counts.get(k, 0) + 1
extra = [f"- `{s}` ({e['kind']}) — {'OLD flat original, to be replaced' if e.get('created','').startswith('9/9') else 'other'}" for s, e in published.items() if s not in planned]
table = "\n".join([
    f"_Auto-generated by `tools/progress.py` at {datetime.datetime.now():%Y-%m-%d %H:%M} — do not hand-edit this block._",
    "", "**Totals:** " + ", ".join(f"{v} {k}" for k, v in counts.items()) + f" (of {len(plan)} planned)",
    "", "| # | Title | Slug | Type | Style | Status | Notes |", "|---|---|---|---|---|---|---|", *rows,
    "", f"**Also in the public catalog ({len(published)} entries total):**", *(extra or ["- (nothing else)"]),
])
doc = open(STATE).read() if os.path.exists(STATE) else "<!-- PROGRESS:START -->\n<!-- PROGRESS:END -->\n"
doc = re.sub(r"<!-- PROGRESS:START -->.*?<!-- PROGRESS:END -->", "<!-- PROGRESS:START -->\n" + table + "\n<!-- PROGRESS:END -->", doc, flags=re.S)
open(STATE, "w").write(doc)
print(f"progress updated: " + ", ".join(f"{v} {k}" for k, v in counts.items()))
